checkoutLocation: src/github.com/hpssjellis/gitpod-hello-ui-demo

workspaceLocation: /

image:
  file: Dockerfile
  
ports:
  - port: 6080
    protocol: "http"

vscode:
  extensions:
    - ms-vscode.cpptools

tasks:
  - command: "go get -v ./... "
  - command: gp await-port 6080            &&
             xterm                         &&
             gp preview $(gp url 6080)     
             
  
  # not getting the following working from the .gitpod.yml file, but it works fine from the command line
  # go run /workspace/src/github.com/hpssjellis/gitpod-hello-ui-demo/main.go 
  
